INSERT INTO USER ( USER_ID ) VALUES ( 10001 );
INSERT INTO USER ( USER_ID ) VALUES ( 10002 );
INSERT INTO USER ( USER_ID ) VALUES ( 10003 );
INSERT INTO USER ( USER_ID ) VALUES ( 10004 );
INSERT INTO USER ( USER_ID ) VALUES ( 10005 );
INSERT INTO USER ( USER_ID ) VALUES ( 10006 );
INSERT INTO USER ( USER_ID ) VALUES ( 10007 );
INSERT INTO USER ( USER_ID ) VALUES ( 10008 );

INSERT INTO ROOM ( ROOM_ID ) VALUES ( 'ROOM1' );
INSERT INTO ROOM ( ROOM_ID ) VALUES ( 'ROOM2' );
INSERT INTO ROOM ( ROOM_ID ) VALUES ( 'ROOM3' );

INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10001, 'ROOM1' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10003, 'ROOM1' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10004, 'ROOM1' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10005, 'ROOM1' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10006, 'ROOM1' );

INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10002, 'ROOM2' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10004, 'ROOM2' );

INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10005, 'ROOM3' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10006, 'ROOM3' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10007, 'ROOM3' );
INSERT INTO USER_IN_ROOM ( USER_ID, ROOM_ID ) VALUES ( 10008, 'ROOM3' );

commit;
