CREATE TABLE IF NOT EXISTS USER (
    USER_ID     INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS ROOM (
    ROOM_ID     VARCHAR(64) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS USERS_IN_ROOM (
    USER_ID     VARCHAR(64) NOT NULL ,
    ROOM_ID     VARCHAR(64) NOT NULL
);

ALTER TABLE USERS_IN_ROOM
ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE USERS_IN_ROOM
ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);

CREATE TABLE IF NOT EXISTS SPREAD_MONEY (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY ,
    TOKEN           CHAR(3) UNIQUE NOT NULL,
    USER_ID         VARCHAR(64) NOT NULL ,
    ROOM_ID         VARCHAR(64) NOT NULL ,
    MONEY           BIGINT NOT NULL ,
    CREATED_DATE    TIMESTAMP DEFAULT NOW() NOT NULL ,
    RECV_EXP_DATE   TIMESTAMP NOT NULL ,
    VIEW_EXP_DATE   TIMESTAMP NOT NULL
);

ALTER TABLE SPREAD_MONEY
    ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);

ALTER TABLE SPREAD_MONEY
    ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);

CREATE TABLE IF NOT EXISTS RECEIVED_MONEY (
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY ,
    TOKEN               VARCHAR(64) NOT NULL ,
    USER_ID             VARCHAR(64) NOT NULL ,
    MONEY               BIGINT NOT NULL ,
);

ALTER TABLE RECEIVED_MONEY
    ADD FOREIGN KEY (TOKEN) REFERENCES SPREAD_MONEY(TOKEN);

ALTER TABLE RECEIVED_MONEY
    ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
