### 받기 API 성공 케이스 - 사용자1
PUT http://localhost:8080/money/spread/XCY
X-USER-ID: 10003
X-ROOM-ID: ROOM1

### 받기 API 성공 케이스 - 사용자2
PUT http://localhost:8080/money/spread/J1i
X-USER-ID: 10005
X-ROOM-ID: ROOM1

### 받기 API 실패 케이스 - 이미 받은 사용자가 다시 요청
PUT http://localhost:8080/money/spread/aaa
X-USER-ID: 10003
X-ROOM-ID: ROOM1

### 받기 API 실패 케이스 - 뿌린 사용자가 요청
PUT http://localhost:8080/money/spread/pDD
X-USER-ID: 10001
X-ROOM-ID: ROOM1

### 받기 API 실패 케이스 - 대화방에 없는 사용자
PUT http://localhost:8080/money/spread/aaa
X-USER-ID: 10008
X-ROOM-ID: ROOM1

### 받기 API 실패 케이스 - 발급되지 않은 토큰
PUT http://localhost:8080/money/spread/www
X-USER-ID: 10003
X-ROOM-ID: ROOM1
